### ISSUE TITLE
Classification loss does not converge

### ISSUE THREAD

**Issue by zhuzzjlu** [ZikangZhou/HiVT#15]
Thanks for your code!
I noticed that you did not record the classified loss. After adding the log of classification loss, I noticed that the classification loss does not converge. This leads to a bad effect of top1 performance.
Do you have any suggestions on the non convergence of classification loss.
Looking forward to your reply~

**Comment by ZikangZhou** [comment]
Yeah, this is indeed an issue, and I feel that cross-entropy loss is not a good choice. For the classification loss, you can try to optimize the NLL of the goal point's mixture of Laplace (detaching the gradient of y_hat and optimizing the classification score only). For the regression part, you can still use the winner-take-all LaplaceNLL loss. I found that this can improve the Brier score a lot. But ultimately, ensembling is the best way to improve the classification score. Some top-ranking methods like WayFormer even ensemble 15 models. However, it is impractical to do ensembling on a real autonomous car, and using ensembling causes unfair comparisons.

**Comment by HHHzp** [comment]
> Yeah, this is indeed an issue, and I feel that cross-entropy loss is not a good choice. For the classification loss, you can try to optimize the NLL of the goal point's mixture of Laplace (detaching the gradient of y_hat and optimizing the classification score only). For the regression part, you can still use the winner-take-all LaplaceNLL loss. I found that this can improve the Brier score a lot. But ultimately, ensembling is the best way to improve the classification score. Some top-ranking methods like WayFormer even ensemble 15 models. However, it is impractical to do ensembling on a real autonomous car, and using ensembling causes unfair comparisons.是的，这确实是一个问题，我觉得交叉熵损失不是一个好的选择。对于分类损失，您可以尝试优化目标点混合拉普拉斯的 NLL（分离 y_hat 的梯度并仅优化分类得分）。对于回归部分，您仍然可以使用赢家通吃的 LaplaceNLL 损失。我发现这可以大大提高 Brier 分数。但最终，集成是提高分类分数的最佳方法。一些顶级的方法，如 WayFormer，甚至集成了 15 个模型。然而，在真实的自动驾驶汽车上进行集成是不切实际的，并且使用集成会导致不公平的比较。

I would like to inquire about the specific implementation of ensemble models.
