### ISSUE TITLE
Can I use the visualization code for result 

### ISSUE THREAD

**Issue by moonseokha** [ZikangZhou/HiVT#16]
Thank you so much for sharing the code.
I would like to use the result visualization in HiVT code, but has the visualization code shown on the github page not been shared? Can you share it ?
Thank U!

**Comment by ZikangZhou** [comment]
Hi @moonseokha,

Sorry for the late reply.

```
def plot_single_vehicle(
    avm: ArgoverseMap, 
    sample_past_trajectory: np.ndarray,  # (20, 2)
    sample_groundtruth: np.ndarray,  # (20, 2) 
    sample_forecasted_trajectories: List[np.ndarray],  # List[(30, 2)]
    sample_city_name: str, 
    ls: str):

    sample_groundtruth = np.concatenate((np.expand_dims(sample_past_trajectory[-1], axis=0), sample_groundtruth), axis=0)
    for sample_forecasted_trajectory in sample_forecasted_trajectories:
        sample_forecasted_trajectory = np.concatenate((np.expand_dims(sample_past_trajectory[-1], axis=0), sample_forecasted_trajectory), axis=0)

    ## Plot history
    obs_len = sample_past_trajectory.shape[0]
    pred_len = sample_groundtruth.shape[0]
    plt.plot(
        sample_past_trajectory[:, 0],
        sample_past_trajectory[:, 1],
        color="#ECA154",
        label="Past Trajectory",
        alpha=1,
        linewidth=3,
        zorder=15,
        ls = ls
    )

    ## Plot future
    plt.plot(
        sample_groundtruth[:, 0],
        sample_groundtruth[:, 1],
        color="#d33e4c",
        label="Ground Truth",
        alpha=1,
        linewidth=3.0,
        zorder=20,
        ls = "--"
    )

    ## Plot prediction
    for j in range(len(sample_forecasted_trajectories)):
        plt.plot(
            sample_forecasted_trajectories[j][:, 0],
            sample_forecasted_trajectories[j][:, 1],
            color="#007672",
            label="Forecasted Trajectory",
            alpha=1,
            linewidth=3.2,
            zorder=15,
            ls = "--"
        )
        
        # Plot the end marker for forcasted trajectories
        plt.arrow(
            sample_forecasted_trajectories[j][-2, 0], 
            sample_forecasted_trajectories[j][-2, 1],
            sample_forecasted_trajectories[j][-1, 0] - sample_forecasted_trajectories[j][-2, 0],
            sample_forecasted_trajectories[j][-1, 1] - sample_forecasted_trajectories[j][-2, 1],
            color="#007672",
            label="Forecasted Trajectory",
            alpha=1,
            linewidth=3.2,
            zorder=15,
            head_width=1.1,
        )
    
    ## Plot the end marker for history
    plt.arrow(
            sample_past_trajectory[-2, 0], 
            sample_past_trajectory[-2, 1],
            sample_past_trajectory[-1, 0] - sample_past_trajectory[-2, 0],
            sample_past_trajectory[-1, 1] - sample_past_trajectory[-2, 1],
            color="#ECA154",
            label="Past Trajectory",
            alpha=1,
            linewidth=3,
            zorder=25,
            head_width=1.0,
        )

    ## Plot the end marker for future
    plt.arrow(
            sample_groundtruth[-2, 0], 
            sample_groundtruth[-2, 1],
            sample_groundtruth[-1, 0] - sample_groundtruth[-2, 0],
            sample_groundtruth[-1, 1] - sample_groundtruth[-2, 1],
            color="#d33e4c",
            label="Ground Truth",
            alpha=1,
            linewidth=3.0,
            zorder=25,
            head_width=1.0,
        )

    ## Plot history context
    for j in range(obs_len):
        lane_ids = avm.get_lane_ids_in_xy_bbox(
            sample_past_trajectory[j, 0],
            sample_past_trajectory[j, 1],
            sample_city_name,
            query_search_range_manhattan=65,
        )
        [avm.draw_lane(lane_id, sample_city_name) for lane_id in lane_ids]

    ## Plot future context
    for j in range(pred_len):
        lane_ids = avm.get_lane_ids_in_xy_bbox(
            sample_groundtruth[j, 0],
            sample_groundtruth[j, 1],
            sample_city_name,
            query_search_range_manhattan=65,
        )
        [avm.draw_lane(lane_id, sample_city_name) for lane_id in lane_ids]
```

**Comment by moonseokha** [comment]
Thank you for reply and good code. :)

**Comment by alfredgu001324** [comment]
Hi, thank you for providing the visualization code. When I implemented it, I found that the output of HiVT (y_hat, x_agent, y_agent) seems to have a different coordinate system or have been augmented. When I try to put them into this piece of code, avm could not find any lane that contain these trajectories. I am wondering how would you convert them back to the coordinate system of Argoverse map? 
Thank you so much!

**Comment by xinfu607** [comment]
> Thank you for reply and good code. :)
Hi,
Could you please release the complete visualization code? Thanks a lot.

**Comment by Joonki0111** [comment]
Hi, i've seen the code and i want to know how to get those samples in the code below

def plot_single_vehicle(
    avm: ArgoverseMap, 
    sample_past_trajectory: np.ndarray,  # (20, 2)
    sample_groundtruth: np.ndarray,  # (20, 2) 
    sample_forecasted_trajectories: List[np.ndarray],  # List[(30, 2)]
    sample_city_name: str, 
    ls: str):

there is no code generating sample_past_trajectory, sample_groundtruth, sample_forecasted_trajectories 
in HiVT repository so i cant run that code.

any help and suggestions will be helping my project alot.
Thanks :)

**Comment by MPCheng-ZW** [comment]
Hi, have you solved this problem? Thank you!
@JoonKi0111 @xinfu607 @moonseokha @ZikangZhou 

> Hi, i've seen the code and i want to know how to get those samples in the code below
> 
> def plot_single_vehicle( avm: ArgoverseMap, sample_past_trajectory: np.ndarray, # (20, 2) sample_groundtruth: np.ndarray, # (20, 2) sample_forecasted_trajectories: List[np.ndarray], # List[(30, 2)] sample_city_name: str, ls: str):
> 
> there is no code generating sample_past_trajectory, sample_groundtruth, sample_forecasted_trajectories in HiVT repository so i cant run that code.
> 
> any help and suggestions will be helping my project alot. Thanks :)

**Comment by yaobaishen** [comment]
> Hi, have you solved this problem? Thank you! [@Joonki0111](https://github.com/Joonki0111) [@xinfu607](https://github.com/xinfu607) [@moonseokha](https://github.com/moonseokha) [@ZikangZhou](https://github.com/ZikangZhou)
> 
> > Hi, i've seen the code and i want to know how to get those samples in the code below
> > def plot_single_vehicle( avm: ArgoverseMap, sample_past_trajectory: np.ndarray, # (20, 2) sample_groundtruth: np.ndarray, # (20, 2) sample_forecasted_trajectories: List[np.ndarray], # List[(30, 2)] sample_city_name: str, ls: str):
> > there is no code generating sample_past_trajectory, sample_groundtruth, sample_forecasted_trajectories in HiVT repository so i cant run that code.
> > any help and suggestions will be helping my project alot. Thanks :)

Has anyone solved the problem? It would be much better if full visualization code is available.

@ZikangZhou sorry for interruption, but could you look at this issue again? thanks.

**Comment by alfredgu001324** [comment]
The visualization instructions [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/trj.md) also let you save the trajectory as pkl files for later visualization. Some modifications are needed (such as get rid of the uncertainty component) but the transformation is the same.

**Comment by yaobaishen** [comment]
> The visualization instructions [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/trj.md) also let you save the trajectory as pkl files for later visualization. Some modifications are needed (such as get rid of the uncertainty component) but the transformation is the same.

@alfredgu001324 thanks for your work! it really saves my day!

**Comment by yaobaishen** [comment]
> > The visualization instructions [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/trj.md) also let you save the trajectory as pkl files for later visualization. Some modifications are needed (such as get rid of the uncertainty component) but the transformation is the same.
> 
> [@alfredgu001324](https://github.com/alfredgu001324) thanks for your work! it really saves my day!

For anyone searches the visualization solution and comes here, please notice the [code](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/trj.md) provided by @alfredgu001324 still needs modification (thanks to the awesome contribution). As the author said "the pickle saving here might only save the ego trajectories. There is a bit of version mismatch". Please move forward to [issue_in_gu's_repo](https://github.com/alfredgu001324/MapUncertaintyPrediction/issues/32) to track the updates, thanks.

**Comment by alfredgu001324** [comment]
I have added a new function that saves all the vehicles' trajectories in each scene and group them accordingly. Thanks for pointing this out.
