### ISSUE TITLE
cudatoolkit=11.1 version problem

### ISSUE THREAD

**Issue by jhih-ching-yeh** [ZikangZhou/HiVT#18]
Excuse me, when I did the following instruction, I got some error.
`conda install pytorch==1.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge`
And the error message is as following.
`Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.1
  - __glibc[version='>=2.17,<3.0.a0']

Current channels:

  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
`

Even I changed my cuda version to 11.0, I still can't solve the problem

Thanks!!

**Comment by ZikangZhou** [comment]
Maybe you can try to install another version of Pytorch: [https://pytorch.org/get-started/previous-versions/](https://pytorch.org/get-started/previous-versions/). Pytorch 1.8 or 1.7 should work well.

**Comment by jhih-ching-yeh** [comment]
May I know your platform? Windows or Linux?
Because after solving this problem, it still has some error about pytorch.

`File "/home/ailab/anaconda3/envs/HiVT/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1145, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly
`

**Comment by ZikangZhou** [comment]
The code is tested on Linux, Ubuntu 18.04. I think this error can be solved by setting pin_memory to False or setting persistent_workers to False. These two parameters are both in train.py.

**Comment by jhih-ching-yeh** [comment]
Your advice works! Thanks a lot!!
