### ISSUE TITLE
Question Regarding to Agent Semantic Attribute

### ISSUE THREAD

**Issue by SwagJ** [ZikangZhou/HiVT#22]
Hi @ZikangZhou,

In your paper, you mention to use semantic attribute of agent as input to agent embedding. However, such semantic attribute is not reflected in your code. Could you please share the method for acquiring semantic attributes? As far as I know, argoverse's agent doesn't have such semantic attribute, do you refer to OBJECT_TYPE in csv file as semantic attribute? 
Thank you in advance. 

Best,

**Comment by ZikangZhou** [comment]
I have tried adding OBJECT_TYPE, but I didn't see any benefit in doing so. Thus, I remove this in the code. The paper still describes it in this way for completeness, because on other new datasets, the object category impacts the performance noticeably.
