### ISSUE TITLE
Question Regarding to Temporal Encoder

### ISSUE THREAD

**Issue by SwagJ** [ZikangZhou/HiVT#23]
Hi @ZikangZhou, 

There is one question regarding to the temporal encoder layer. When computing the attention in temporal encoder layer, all the agent within the batch is calculated instead of batch-wise attention, I was wondering fusing such batched information? Thank you in advance. 

Best,

**Comment by ZikangZhou** [comment]
The temporal encoder performs attention across different time steps within the same agent, so there isn't any information fusion across different agents.
