### ISSUE TITLE
question regarding Laplace distribution

### ISSUE THREAD

**Issue by dichencd** [ZikangZhou/HiVT#24]
Hi @ZikangZhou, when calculating regression loss, you seem to model x and y as independent univariate Laplace distributions if I understand correctly based on your code. I wonder what would be the intuition behind such a choice versus considering x & y jointly as a multivariate Laplace distribution? Thank you very much for your comments in advance!

**Comment by ZikangZhou** [comment]
Hi,

Thanks for your interest! I would say it's for simplicity, although this assumption is somewhat counter-intuitive. You can try to model x & y jointly. I think many people are interested in such an ablation study!

**Comment by dichencd** [comment]
I see. Thanks!
