### ISSUE TITLE
Leaderboard Submission Code

### ISSUE THREAD

**Issue by jiachenwei** [ZikangZhou/HiVT#25]
Would you like to provide Leaderboard Submission Code？ I test the checkpoint and submit to leaderboader, but got some errors.

**Comment by ZikangZhou** [comment]
Honestly, I didn't keep that part of the code, but you can refer to [this issue](https://github.com/ZikangZhou/HiVT/issues/14).

**Comment by jiachenwei** [comment]
Thank you very much.

**Comment by jiachenwei** [comment]
> Honestly, I didn't keep that part of the code, but you can refer to [this issue](https://github.com/ZikangZhou/HiVT/issues/14).

Thank you very much.

**Comment by Porphy** [comment]
> > Honestly, I didn't keep that part of the code, but you can refer to [this issue](https://github.com/ZikangZhou/HiVT/issues/14).
> 
> Thank you very much.

Have you solved the problem？And would you like to provide your Leaderboard Submission Code？Thanks

**Comment by manikandanhu2016** [comment]
can any one help to for leader board submission code ?
