### ISSUE TITLE
Why Euclidean distance needed to be conculated after Huffman Distance? 

### ISSUE THREAD

**Issue by SevenTailCat** [ZikangZhou/HiVT#27]
Hello, thank you for your amazing working.
I have a question after read your code. The set of points with Euclidean distance less than radius is contained in the set of points with Huffman distance less than radius.
If only conculate the huffman distance, will it be more quickly?
Your Sincerely

**Comment by ZikangZhou** [comment]
You're right. But I don't think the speed would be significantly different if using GPU to do the calculation, because the computation is highly parallel.

**Comment by SevenTailCat** [comment]
Thank you for your rep.
And I am still curious ...
Will the block conculated by Huffman distance influent the result of model?

**Comment by SevenTailCat** [comment]
> 

Or...uhhh, I think I want to ask that why you conculate the euclidean distance?

**Comment by ZikangZhou** [comment]
There isn't any specific reason. You can try both, but I guess the performance would be very similar.

**Comment by SevenTailCat** [comment]
Thank you very much.

**Comment by SevenTailCat** [comment]
I will have a try.
