### ISSUE TITLE
Qualitative Results Visualization

### ISSUE THREAD

**Issue by MeycL** [ZikangZhou/HiVT#30]
Thank you very much for your work. I've been doing related work recently, can you please provide a visualization of the Qualitative Results section? I would be very grateful if you could!

**Comment by ZikangZhou** [comment]
Do you mean you want the code for generating the visualization results?

**Comment by MeycL** [comment]
![image](https://user-images.githubusercontent.com/96134259/212715311-0d8fedb1-d018-4dc0-97e4-661218124eb0.png)
Yes, just like this picture. Thank you very much if you could.

**Comment by ZikangZhou** [comment]
Sure, you can refer to [this issue](https://github.com/ZikangZhou/HiVT/issues/16). Feel free to ask me if you have further questions.

**Comment by MeycL** [comment]
Thank you for reply.

**Comment by MPCheng-ZW** [comment]
Hi, do you produce the visualization results now? If so, could you tell me your method? Thank you very much! @MeycL
