### ISSUE TITLE
torch.load bottleneck?

### ISSUE THREAD

**Issue by moonseokha** [ZikangZhou/HiVT#33]
Hi.
I'm interested in your research, so I'm looking at it hard. 
But when I start training code, at first, gpu is used as a high utilization as data enters well through torch.load,  as steps progress,  data loading time of the torch.load becomes longer and gpu utill 0, a bottleneck occurs. Have you ever had a problem like this?

It is the estimated time required and gpu util before the  bottleneck.
<img width="587" alt="스크린샷 2023-01-23 오후 4 38 06" src="https://user-images.githubusercontent.com/68099131/213988744-690ad660-28bc-4e64-b31d-4a999ddbfac8.png">
<img width="842" alt="스크린샷 2023-01-23 오후 4 38 26" src="https://user-images.githubusercontent.com/68099131/213988750-96ab1a1c-c350-4083-bdde-6648ad71f71f.png">

After bottleneck
<img width="580" alt="스크린샷 2023-01-23 오후 4 37 58" src="https://user-images.githubusercontent.com/68099131/213988964-6f05edd6-4a06-4e71-8b7f-c30267fae531.png">
<img width="864" alt="스크린샷 2023-01-23 오후 4 38 17" src="https://user-images.githubusercontent.com/68099131/213989155-319e8a7b-8332-43d8-ae16-7309e198faf2.png">

Thank U!

**Comment by ggosjw** [comment]
Hi, i have the same issue. May I how do you solve this problem?

**Comment by Liwen-Xiao** [comment]
I have the same problem. This seems to be the bottleneck that comes with mechanical hard drives
![image](https://github.com/user-attachments/assets/ef8b33df-4fe7-4fed-b424-5ef968c48ea1)
