### ISSUE TITLE
HiVT map-free customization 

### ISSUE THREAD

**Issue by javierAraluce** [ZikangZhou/HiVT#46]
Hello, first of all, thank you for your excellent work and dedication in making it openly available for the community to use.

I was wondering how I could adapt your code so that it can be evaluated in a version without a map, as they claim in the following [paper](https://arxiv.org/pdf/2307.09831.pdf). They have compared HiVT with your model in a way that doesn't use a map.

Thanks in advance

**Comment by EtienneDS** [comment]
I believe the author(s) have moved on to their new algorithm [QCNet](https://github.com/ZikangZhou/QCNet) and such won't really put too much work into this one anymore.

I believe to make it work without map all you need to do is remove the ALEncoder in local_encoder.py :
https://github.com/ZikangZhou/HiVT/blob/6876656ce7671982ebdc29113aaaa028c2931518/models/local_encoder.py#L64-L68
https://github.com/ZikangZhou/HiVT/blob/6876656ce7671982ebdc29113aaaa028c2931518/models/local_encoder.py#L93-L96

You can also remove the mapping sections from the data preprocessing if you are using Argoverse:
https://github.com/ZikangZhou/HiVT/blob/6876656ce7671982ebdc29113aaaa028c2931518/datasets/argoverse_v1_dataset.py#L152-L157

With this you should be able to run the code without map information, though I cannot say if this is the *best* way as to get optimal results.
